#!/bin/bash

NODENAME='temp-node'

echo 'UPDATE AND INSTALL UTILS'
sudo apt-get -yq update
sudo apt-get -yq install curl ca-certificates

echo 'SET HOSTNAME'
echo $NODENAME | sudo tee /etc/hostname
echo "$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) $NODENAME" | sudo tee -a /etc/hosts
sudo hostname $NODENAME

echo 'INSTALL LINUX IMAGE EXTRA'
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
sudo apt-get -yq update
sudo apt-get -yq install linux-image-extra-$(uname -r)
sudo apt-get -yq update

echo 'INSTALL DOCKER'
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker ubuntu

echo 'DONE'
