#!/bin/bash

echo 'INSTALL LINUX IMAGE EXTRA'
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
sudo apt-get -yq update
sudo apt-get -yq install linux-image-extra-$(uname -r)
sudo apt-get -yq update

echo 'INSTALL DOCKER'
curl -sSL https://get.docker.com | sh
usermod -aG docker ubuntu

echo 'DONE'
